#!/bin/bash -v
{
curl -sNL http://eulersharp.sourceforge.net/2009/12dtb/test-dl-1000000.n3 > dl.n3
eye --nope --turtle dl.n3 --pcode dl.n3p
/usr/bin/time -f "sec=%e0 kB=%M cpu=%P" eye --nope --n3p dl.n3p subclass-rules.n3 --query query.n3
/usr/bin/time -f "sec=%e0 kB=%M cpu=%P" eyebrow --nope --n3p dl.n3p subclass-rules.n3 --query query.n3

eye --nope --turtle dl.n3 --query parteval-subclass.n3 > dt.n3
swipl --stack-limit=8G -g main /opt/eye/src/eye.pl -- --nope dt.n3 --pcode dt.n3p
/usr/bin/time -f "sec=%e0 kB=%M cpu=%P" eye --nope facts.n3 --n3p dt.n3p --query query.n3
/usr/bin/time -f "sec=%e0 kB=%M cpu=%P" eyebrow --nope facts.n3 --n3p dt.n3p --query query.n3

} |& tee test.txt
